# Generated by Django 5.2.4 on 2025-07-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
