# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dbdLdLPy2PUsNB7W4JK9J46um46_TnfG
"""

import pandas as pd
import numpy as np

path = '/content/drive/MyDrive/ml_sessional/salaries.csv'
df = pd.read_csv(path)
#df.head()

output = df['salary_more_then_100k']
#output.head(2)

input = df[['company', 'job', 'degree']]
#input.head()

from sklearn.preprocessing import LabelEncoder
label_company = LabelEncoder()
label_job = LabelEncoder()
label_degree = LabelEncoder()

input['company'] = label_company.fit_transform(input['company'])
input['job'] = label_job.fit_transform(input['job'])
input['degree'] = label_degree.fit_transform(input['degree'])

input.head()

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(input, output, test_size=0.2)

from sklearn.tree import DecisionTreeClassifier
obj = DecisionTreeClassifier()
obj.fit(x_train, y_train)

prediction= obj.predict(x_test)
print(prediction)

print(y_test)

obj.score(x_test, y_test)