# -*- coding: utf-8 -*-
"""K-means_G1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZt3XoCZvXZ39gW_1K-cue_wsIVNaQ7_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path = '/content/drive/MyDrive/ml_sessional/income.csv'
df= pd.read_csv(path)
df.head()

plt.scatter(df['Age'],df['Income($)'])
plt.xlabel('Age')
plt.ylabel('Income')
# plt.show()

from sklearn.cluster import KMeans
km = KMeans(n_clusters=3)
y_predicted = km.fit_predict(df[['Age','Income($)']])
print(y_predicted)

df['Cluster'] = y_predicted
df.head()

df1=df[df.Cluster==0]
df2=df[df.Cluster==1]
df3=df[df.Cluster==2]

plt.scatter(df1['Age'],df1['Income($)'],color='green', label='Cluster 0')
plt.scatter(df2['Age'],df2['Income($)'],color='red', label='Cluster 1')
plt.scatter(df3['Age'],df3['Income($)'],color='black', label='Cluster 2')

plt.xlabel('Age')
plt.ylabel('Income')
plt.legend()
# plt.show()

"""min max scaler for change the high value, law=x-Xmin/Xmax-Xmin"""

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

df['Income($)'] = scaler.fit_transform(df[['Income($)']])

df['Age'] = scaler.fit_transform(df[['Age']])

df.head()

km = KMeans(n_clusters=3)
y_predicted = km.fit_predict(df[['Age','Income($)']])
print(y_predicted)

df['cluster']=y_predicted

df1=df[df.cluster==0]
df2=df[df.cluster==1]
df3=df[df.cluster==2]

plt.scatter(df1['Age'],df1['Income($)'],color='green', label='Cluster 0')
plt.scatter(df2['Age'],df2['Income($)'],color='red', label='Cluster 1')
plt.scatter(df3['Age'],df3['Income($)'],color='black', label='Cluster 2')

# to show center

plt.scatter(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color='purple',marker='*',label='centroid')

plt.xlabel('Age')
plt.ylabel('Income')
plt.legend()
# plt.show()