# -*- coding: utf-8 -*-
"""KN-Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GFDQl3Ry7EesnAApFYQS8WI2GzIsfvzK
"""

import pandas as pd
import numpy as np

path = '/content/drive/MyDrive/ml_sessional/diabetes.csv'
df= pd.read_csv(path)

change_zero = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
for column in change_zero:
  df[column] = df[column].replace(0, np.nan)
  mean = int(df[column].mean(skipna=True))
  df[column] = df[column].replace(np.nan,mean)

#df.head

from sklearn.model_selection import train_test_split
X = df.iloc[:,0:8]
y = df.iloc[:,8]
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=0,test_size=0.2)

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=11,p=2,metric='euclidean')
classifier.fit(X_train,y_train)

classifier.predict(X_test)