# -*- coding: utf-8 -*-
"""logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YMxEN5CzFAFVMKUEc9bN9PR8RYZq7GC-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

path= '/content/drive/MyDrive/ml_sessional/insurance_data.csv'
df = pd.read_csv(path)
df.head()

plt.xlabel('Age')
plt.ylabel('bought Insurance')
plt.scatter(df['age'], df['bought_insurance'])

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(df[['age']], df['bought_insurance'])

prediction = logreg.predict(df[['age']])
actual = np.array(df['bought_insurance'])
print(actual,prediction,sep="\n")

logreg.intercept_

logreg.coef_

import math

x= -5.26279121+0.13546543*22

sigmoid=1/(1+math.exp(-x))
print(sigmoid)

if sigmoid>=0.5:
  print(1)
else:
  print(0)