# -*- coding: utf-8 -*-
"""NaiveBayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11P0kNhZOVhJzGjI_f2uzq421dVVKdvzy

PREPARE THE DATAFRAME FOR titanic.csv DATASET
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path = '/content/drive/MyDrive/ml_sessional/titanic.csv'
df= pd.read_csv(path)
# print(df)
df.head()

df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis='columns', inplace=True)
df.head()

input = df.drop('Survived', axis='columns')
target = df.Survived
input.head()

new = pd.get_dummies(input.Sex).astype(int)
new.head()

input.drop(['Sex'], inplace=True, axis='columns')
input.head()

input = pd.concat([input,new], axis='columns')
input.head()

input['Age'] = input.Age.fillna(input.Age.mean())
input.head()

input.Age

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.3)

from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(input, target)

prediction = model.predict(X_test)
print(prediction)
print(np.array(y_test))

model.score(X_test, y_test)

model.predict_proba(X_test)