# -*- coding: utf-8 -*-
"""salary_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rW3LFzh1Q1TOkCvkhGGPCR5YictY3r4e
"""

import numpy as np
import pandas as pd

path = '/content/Salary_Data.csv'
df =pd.read_csv(path)

q1 = df['Years of Experience'].quantile(0.25)
q3 = df['Years of Experience'].quantile(0.75)
iqr = q3 - q1

print(q1, q3,iqr)

lower_bound = q1 - 1.5*iqr
upper_bound = q3 + 1.5*iqr

print(lower_bound, upper_bound)

newdf = df[(df['Years of Experience']>lower_bound) & (df['Years of Experience']<upper_bound)]

"""Pandas"""

df =df.rename(columns={'Years of Experience':'Experience'})

df.tail()

df.shape

df.info()

df=df.drop(columns='Unnamed: 0')

df.describe()

df.isnull().sum()

df['Experience'].unique()