# Generated by Django 5.2.4 on 2025-07-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
